# Generated by Django 4.2.18 on 2025-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='additional_taught',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='school.additionalactivity', verbose_name='Дополнительные услуги'),
        ),
    ]
