# Generated by Django 4.2.18 on 2025-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_teacher_additional_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teachers_images/', verbose_name='Фото преподавателя'),
        ),
    ]
