# Generated by Django 4.2.18 on 2025-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/blog'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/teacher', verbose_name='Фото преподавателя'),
        ),
    ]
