# Generated by Django 4.2.18 on 2025-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_blog_image_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('announce', 'Объявления'), ('event', 'Мероприятия'), ('schedule', 'Расписание')], default='blog', max_length=100),
        ),
    ]
