# Generated by Django 4.2.18 on 2025-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
        ),
    ]
