# Generated by Django 4.2.18 on 2025-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_full_name', models.CharField(max_length=255, verbose_name='ФИО родителя')),
                ('parent_passport', models.CharField(max_length=50, verbose_name='Паспортные данные родителя')),
                ('student_full_name', models.CharField(max_length=255, verbose_name='ФИО ученика')),
                ('student_passport', models.CharField(max_length=50, verbose_name='Паспортные данные ученика')),
                ('grade_applied', models.CharField(max_length=10, verbose_name='Класс для поступления')),
                ('attached_files', models.FileField(blank=True, null=True, upload_to='admission_files/', verbose_name='Прикреплённые файлы')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
        ),
    ]
