# Generated by Django 4.2.18 on 2025-01-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='admission_files/', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Класс')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher', verbose_name='Классный руководитель')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО ученика')),
                ('student_passport', models.CharField(max_length=50, verbose_name='Номер паспорт')),
                ('student_id', models.CharField(max_length=50, verbose_name='ИН паспорта')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('grade', models.CharField(max_length=10, verbose_name='Класс')),
                ('login', models.CharField(blank=True, max_length=50, null=True, verbose_name='Логин')),
            ],
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email родителя'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='parent_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИН родителя'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='student_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес ученика'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИН ученика'),
        ),
        migrations.RemoveField(
            model_name='admissionrequest',
            name='attached_files',
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='parent_passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт родителя'),
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='student_passport',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Паспорт ученика'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=20, verbose_name='День недели')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('start_time', models.TimeField(verbose_name='Время начала урока')),
                ('end_time', models.TimeField(verbose_name='Время окончания урока')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.class', verbose_name='Класс')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher', verbose_name='Учитель')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='archives/', verbose_name='Архив с документами')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='Ученик')),
            ],
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='attached_files',
            field=models.ManyToManyField(to='school.admissionfile', verbose_name='Прикреплённые файлы'),
        ),
    ]
