# Generated by Django 4.2.18 on 2025-01-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_remove_admissionrequest_attached_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionrequest',
            name='student_full_name',
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='student_first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя ученика'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='student_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия ученика'),
        ),
        migrations.AddField(
            model_name='admissionrequest',
            name='student_patronymic',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество ученика'),
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email родителя или ученика'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='additional_taught',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='school.additionalactivity', verbose_name='Дополнительные услуги'),
        ),
    ]
