# Generated by Django 4.2.18 on 2025-01-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_admissionrequest_student_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionrequest',
            name='student_address',
        ),
    ]
