# Generated by Django 4.2.18 on 2025-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_uploadedfile_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrequest',
            name='is_approved',
            field=models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], max_length=10, verbose_name='Подтверждена'),
        ),
    ]
