# Generated by Django 4.2.18 on 2025-01-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_documentarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentarchive',
            name='archive_admission',
            field=models.BooleanField(default=False, verbose_name='Документы на поступление'),
        ),
    ]
