# Generated by Django 4.2.18 on 2025-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_remove_student_login_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionrequest',
            old_name='student_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='admissionrequest',
            old_name='student_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='admissionrequest',
            old_name='student_patronymic',
            new_name='patronymic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя ученика'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия ученика'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчество ученика'),
        ),
    ]
