# Generated by Django 4.2.18 on 2025-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_rename_student_first_name_admissionrequest_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email родителя или ученика'),
        ),
    ]
