# Generated by Django 4.2.18 on 2025-01-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_student_parent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.PositiveIntegerField(default=25, verbose_name='Максимальное количество студентов'),
        ),
    ]
