# Generated by Django 4.2.18 on 2025-01-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_remove_student_grade_student_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentarchive',
            name='archive_admission',
        ),
    ]
