# Generated by Django 4.2.18 on 2025-01-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_uploadedfile_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('admission', 'Поступление'), ('management', 'Руководство '), ('student', 'Студентам'), ('teacher', 'Учителям')], max_length=10, null=True, verbose_name='Тип документа'),
        ),
    ]
