# Generated by Django 4.2.18 on 2025-01-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_alter_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Номер урока'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='office',
            field=models.PositiveIntegerField(null=True, verbose_name='Кабинет'),
        ),
    ]
