# Generated by Django 4.2.18 on 2025-01-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_schedule_lesson_number_schedule_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('announce', 'Объявления'), ('event', 'Мероприятия')], default='blog', max_length=100),
        ),
    ]
