# Generated by Django 4.2.18 on 2025-01-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('announce', 'Объявления'), ('event', 'Мероприятия'), ('schedule', 'Расписание')], default='blog', max_length=100),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Предмет'),
        ),
    ]
