# Generated by Django 4.2.18 on 2025-01-25 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_alter_blog_category_alter_schedule_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subject', verbose_name='Предмет'),
        ),
    ]
