# Generated by Django 4.2.18 on 2025-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_schedule_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='Предмет'),
        ),
    ]
