# Generated by Django 4.2.18 on 2025-01-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_alter_schedule_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='additional_taught',
        ),
        migrations.AddField(
            model_name='additionalactivity',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='activities', to='school.uploadedfile', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='additionalactivity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='additionalactivity',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='school.teacher', verbose_name='Учитель'),
        ),
    ]
