# Generated by Django 4.2.18 on 2025-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_remove_teacher_additional_taught_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('news', 'Новости'), ('announce', 'Объявления'), ('event', 'Мероприятия')], default='blog', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('admission', 'Поступление'), ('management', 'Руководство '), ('student', 'Студентам'), ('teacher', 'Учителям'), ('paid_service', 'Платные услуги')], max_length=15, null=True, verbose_name='Тип документа'),
        ),
    ]
