# Generated by Django 4.2.18 on 2025-01-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_alter_blog_category_alter_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='associated_files', to='school.additionalactivity', verbose_name='Платные услуги'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='apply_to_all_services',
            field=models.BooleanField(default=False, verbose_name='Применить ко всем платным услугам'),
        ),
        migrations.AlterField(
            model_name='additionalactivity',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='related_activities', to='school.uploadedfile', verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('admission', 'Поступление'), ('management', 'Руководство'), ('student', 'Студентам'), ('teacher', 'Учителям'), ('paid_service', 'Платные услуги')], max_length=15, null=True, verbose_name='Тип документа'),
        ),
    ]
