# Generated by Django 4.2.18 on 2025-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_uploadedfile_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название награды')),
                ('description', models.TextField(blank=True, verbose_name='Описание награды')),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/', verbose_name='Фото награды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название лицензии')),
                ('description', models.TextField(blank=True, verbose_name='Описание лицензии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='licenses/', verbose_name='Фото лицензии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Лицензия',
                'verbose_name_plural': 'Лицензии',
            },
        ),
    ]
