# Generated by Django 4.2.18 on 2025-01-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_schoolcontactinfo_alter_award_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcontactinfo',
            name='begin_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AddField(
            model_name='schoolcontactinfo',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Конец рабочего дня'),
        ),
    ]
