# Generated by Django 4.2.18 on 2025-01-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_schoolcontactinfo_begin_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('director', 'Директор'), ('management', 'Руководство'), ('teacher', 'Учитель')], max_length=50, verbose_name='Должность'),
        ),
    ]
