# Generated by Django 4.2.18 on 2025-01-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_alter_teacher_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('accessibility', models.CharField(choices=[('partial', 'Частичная'), ('full', 'Полная'), ('none', 'Отсутствует')], default='partial', max_length=255, verbose_name='Приспособленность для инвалидов')),
                ('equipment', models.ManyToManyField(to='school.equipment', verbose_name='Оснащенность кабинета')),
                ('school_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolcontactinfo', verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование кабинета')),
                ('accessibility', models.CharField(choices=[('partial', 'Частичная'), ('full', 'Полная'), ('none', 'Отсутствует')], default='partial', max_length=255, verbose_name='Приспособленность для инвалидов')),
                ('equipment', models.ManyToManyField(to='school.equipment', verbose_name='Оснащенность кабинета')),
                ('school_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolcontactinfo', verbose_name='Адрес')),
            ],
        ),
    ]
