# Generated by Django 4.2.18 on 2025-01-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0041_equipment_practicalobject_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('classroom', 'Кабинет'), ('practical_object', 'Объект для практических занятий')], default='classroom', max_length=50, verbose_name='Тип объекта')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование кабинета')),
                ('accessibility', models.CharField(choices=[('partial', 'Частичная'), ('full', 'Полная'), ('none', 'Отсутствует')], default='partial', max_length=255, verbose_name='Приспособленность для инвалидов')),
                ('equipment', models.ManyToManyField(to='school.equipment', verbose_name='Оснащенность кабинета')),
                ('school_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolcontactinfo', verbose_name='Адрес')),
            ],
        ),
        migrations.RemoveField(
            model_name='practicalobject',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='practicalobject',
            name='school_contact',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='PracticalObject',
        ),
    ]
