# Generated by Django 4.2.18 on 2025-01-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_facility_remove_practicalobject_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='access_level',
            field=models.CharField(choices=[('all', 'Все пользователи'), ('students', 'Только студенты'), ('teachers', 'Только учителя'), ('management', 'Только руководство')], default='all', max_length=15, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='name_file',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/documents/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('local_regulations', 'Локальные нормативные акты'), ('paid_service', 'Платные услуги')], max_length=50, null=True, verbose_name='Категория документа'),
        ),
    ]
