# Generated by Django 4.2.18 on 2025-01-27 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0043_uploadedfile_access_level_uploadedfile_name_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalactivity',
            name='documents',
        ),
        migrations.AddField(
            model_name='additionalactivity',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_activities', to='school.uploadedfile', verbose_name='Документы'),
        ),
    ]
